service: image-analisys
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - rekognition:DetectLabels
        Resource: '*'
      - Effect: Allow
        Action:
          - traslate:TranslateText
        Resource: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
